spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security_demo?charset=utf8mb4
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
